remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "contrast"

locale: "en-US"
title: "Home"
baseurl: ""
url: "https://aakash2016.github.io"

author:
  name             : "Aakash Agrawal"
  bio              : "MS Data Science UCSD"
  avatar           : "/assets/images/aakash.jpg"
  location         : "San Diego, California, US"
  email            : "akash.gagrawal@gmail.com"
  linkedin         : "akash2016123/"
  github           : "aakash2016"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
