theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"

locale: "en-US"
title: "Home"
baseurl: ""
url: "https://aakash2016.github.io"

author:
  name             : "Aakash Agrawal"
  bio              : "MS Data Science UCSD"
  avatar           : "/assets/images/aakash.jpg"
  location         : "San Diego, California, US"
  email            : "akash.gagrawal@gmail.com"
  linkedin         : "https://www.linkedin.com/in/akash2016123/"
  github           : "https://github.com/aakash2016"
